<?php

/**
 * @file
 * Simple modal window.
 */
 
/**
 *  Implementation of hook_theme()
 */
function custom_modal_theme($existing, $type, $theme, $path) {
	
  $themes = array();
  //example usage: theme('custom_modal_window', array('vars' => array('id' => 'blank', 'content' => t("It's a blank modal window"))));
  // link: <a href="#blank" name="modal">Example</a>
  $themes['custom_modal_window'] = array(
    'template' => 'custom_modal',
    'variables' => array(
	  'vars' => NULL,
	),
  );

  return $themes;
}

/**
 * Preprocess function to custom_modal_window
 */
function custom_modal_preprocess_custom_modal_window(&$vars) {
  drupal_add_css(drupal_get_path('module', 'custom_modal') . '/css/custom_modal.css');	
  drupal_add_js(drupal_get_path('module', 'custom_modal') . '/js/custom_modal.js');
}
